#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo 'styling, testing and building your project before commiting'

#check prettier
npm run check-format ||
{
  echo 'Prettier Check failed, Run npm run format, add changes and try commit again'
  false;
}

# Check ESLint
npm run check-lint ||
{
  echo 'ESLint Check failed, Make the required changes listed above, add changes and try to commit again'
  false;
}

# Check tsconfig
npm run check-types ||
{
  echo "Failed type check, Make the changes require above, add changes and try"
  false;
}

npm run build ||
{
  echo "Your build failed, view the error above"
  false;
}

echo "Success Commit"
